{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "MAIN_ROUTER", "label": "Main Router Hostaname", "query": "${VAR_MAIN_ROUTER}" },
   { "name": "MAIN_WIFI_AP", "label": "Main Wifi AP Hostname", "query": "${VAR_MAIN_WIFI_AP}" },
   { "name": "WAN_INTERFACE", "label": "Name of WAN Interface", "query": "${VAR_WAN_INTERFACE}" }
  ]
 },
 "panels": [
  {
   "title": "Uptime [RB2011]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Sent [24h]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$WAN_INTERFACE$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Recv [24h]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$WAN_INTERFACE$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi Sent [24h]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "wlan1" }
     ]
    }
   ]
  },
  {
   "title": "WiFi Recv [24h]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "wlan1" }
     ]
    }
   ]
  },
  {
   "title": "Uptime [RBmAPL]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$WAN_INTERFACE$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Recv",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$WAN_INTERFACE$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi Sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "wlan1" }
     ]
    }
   ]
  },
  {
   "title": "WiFi Recv",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "wlan1" }
     ]
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "mtxrDHCPLeaseCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage [RB2011]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage [RBmAPL]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage [RB2011]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature [RB2011]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_system",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Overal CCQ [RBmAPL]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_wifi",
     "select": [
      [
       { "params": [ "mtxrWlApOverallTxCCQ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ntwrk_wifi",
     "select": [
      [
       { "params": [ "mtxrWlApAuthClientCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "WAN.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=~", "value": "/^$WAN_INTERFACE$/" },
      { "condition": "AND", "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "WIFI.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=", "value": "wlan1" },
      { "condition": "AND", "key": "sysName", "operator": "=~", "value": "/^$MAIN_WIFI_AP$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*(-1)" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=~", "value": "/^ether*/" },
      { "condition": "AND", "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping (average response)",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "Ping to $tag_url",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Resolve (query time)",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping (average response)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Ping to $tag_url",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Resolve (query time)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Query to $tag_server",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}